name: e2e-test

on:
  push:
    branches: ["main"]

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: simulator-ios
  maestro_test:
    needs: [build_ios]
    type: maestro
    environment: production
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }} # required
      flow_path: ["./maestro/login-flow.yml"]

    